version: '3.3'
services:
  web:
    container_name: mudrock-app
    build:
          context: ./
          dockerfile: ./php.Dockerfile
    volumes:
      - ./:/var/www/html/
    ports:
      - 8000:80

volumes:
  html: