version: '3.3'
services:
  web:
    container_name: php-7.4
    build:
          context: ./
          dockerfile: ./php.Dockerfile
    volumes:
      - ./:/var/www/html/
    ports:
      - 8000:80

  mysql:
      container_name: mysql-5.6
      image: mysql:5.6.35
      network_mode: host
      restart: 'no'
      tty: true
      expose:
        - 3306
      environment:
        MYSQL_ROOT_PASSWORD: root
      volumes:
        - mysql:/var/lib/mysql

volumes:
  mysql:
  html: